// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildPlatform(arg1:string,arg2:string):Promise<void>;

export function CdIntoFolder(arg1:string):Promise<void>;

export function CreateNewFile(arg1:string,arg2:string):Promise<void>;

export function CreateNewFolder(arg1:string,arg2:string):Promise<void>;

export function CreateProject(arg1:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function DownloadAndRunTool(arg1:string,arg2:string):Promise<void>;

export function ExecuteCommand(arg1:string):Promise<void>;

export function GetFlutterVersion():Promise<string>;

export function GetToolsByVersion():Promise<Array<Record<string, string>>>;

export function OpenFolder():Promise<main.FileNode>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function RunDebug(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
