// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPlatform(arg1, arg2) {
  return window['go']['main']['App']['BuildPlatform'](arg1, arg2);
}

export function CdIntoFolder(arg1) {
  return window['go']['main']['App']['CdIntoFolder'](arg1);
}

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function CreateNewFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFolder'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DownloadAndRunTool(arg1, arg2) {
  return window['go']['main']['App']['DownloadAndRunTool'](arg1, arg2);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetFlutterVersion() {
  return window['go']['main']['App']['GetFlutterVersion']();
}

export function GetToolsByVersion() {
  return window['go']['main']['App']['GetToolsByVersion']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2);
}

export function RunDebug(arg1, arg2) {
  return window['go']['main']['App']['RunDebug'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
