name: MacOS Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build
        run: |
          cd frontend && npm install && cd ..
          wails build -platform darwin/universal
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS-App
          path: build/bin/*
